source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sqlite3'
gem 'rack'
gem 'thin'
gem 'protected_attributes'

group :development do
  #
end

group :production do
  #
end
